using System;

namespace Hg;

public static class HgExtensions
{
    public static Func<string, Node> tag => tagName => new Node(tagName);

    public static Node @base => tag("base");
    public static Node @break => tag("break");
    public static Node @object => tag("object");
    public static Node abbreviation => tag("abbreviation");
    public static Node acronym => tag("acronym");
    public static Node address => tag("address");
    public static Node anchor => tag("anchor");
    public static Node applet => tag("applet");
    public static Node area => tag("area");
    public static Node article => tag("article");
    public static Node aside => tag("aside");
    public static Node audio => tag("audio");
    public static Node basefont => tag("basefont");
    public static Node bdi => tag("bdi");
    public static Node bdo => tag("bdo");
    public static Node bgsound => tag("bgsound");
    public static Node big => tag("big");
    public static Node blockquote => tag("blockquote");
    public static Node body => tag("body");
    public static Node bold => tag("bold");
    public static Node button => tag("button");
    public static Node canvas => tag("canvas");
    public static Node caption => tag("caption");
    public static Node center => tag("center");
    public static Node cite => tag("cite");
    public static Node code => tag("code");
    public static Node colgroup => tag("colgroup");
    public static Node column => tag("column");
    public static Node comment => tag("comment");
    public static Node data => tag("data");
    public static Node datalist => tag("datalist");
    public static Node dd => tag("dd");
    public static Node define => tag("define");
    public static Node delete => tag("delete");
    public static Node details => tag("details");
    public static Node dialog => tag("dialog");
    public static Node dir => tag("dir");
    public static Node div => tag("div");
    public static Node dl => tag("dl");
    public static Node dt => tag("dt");
    public static Node embed => tag("embed");
    public static Node fieldset => tag("fieldset");
    public static Node figcaption => tag("figcaption");
    public static Node figure => tag("figure");
    public static Node font => tag("font");
    public static Node footer => tag("footer");
    public static Node form => tag("form");
    public static Node frame => tag("frame");
    public static Node frameset => tag("frameset");
    public static Node head => tag("head");
    public static Node header => tag("header");
    public static Node heading => tag("heading");
    public static Node hgroup => tag("hgroup");
    public static Node hr => tag("hr");
    public static Node html => tag("html");
    public static Node Iframes => tag("Iframes");
    public static Node image => tag("image");
    public static Node input => tag("input");
    public static Node ins => tag("ins");
    public static Node isindex => tag("isindex");
    public static Node italic => tag("italic");
    public static Node kbd => tag("kbd");
    public static Node keygen => tag("keygen");
    public static Node label => tag("label");
    public static Node legend => tag("legend");
    public static Node list => tag("list");
    public static Node main => tag("main");
    public static Node mark => tag("mark");
    public static Node marquee => tag("marquee");
    public static Node menuitem => tag("menuitem");
    public static Node meta => tag("meta");
    public static Node meter => tag("meter");
    public static Node nav => tag("nav");
    public static Node nobreak => tag("nobreak");
    public static Node noembed => tag("noembed");
    public static Node noscript => tag("noscript");
    public static Node optgroup => tag("optgroup");
    public static Node option => tag("option");
    public static Node output => tag("output");
    public static Node paragraphs => tag("paragraphs");
    public static Node param => tag("param");
    public static Node phrase => tag("phrase");
    public static Node pre => tag("pre");
    public static Node progress => tag("progress");
    public static Node q => tag("q");
    public static Node rp => tag("rp");
    public static Node rt => tag("rt");
    public static Node ruby => tag("ruby");
    public static Node s => tag("s");
    public static Node samp => tag("samp");
    public static Node script => tag("script");
    public static Node section => tag("section");
    public static Node small => tag("small");
    public static Node source => tag("source");
    public static Node spacer => tag("spacer");
    public static Node span => tag("span");
    public static Node strike => tag("strike");
    public static Node strong => tag("strong");
    public static Node style => tag("style");
    public static Node sub => tag("sub");
    public static Node summary => tag("summary");
    public static Node sup => tag("sup");
    public static Node svg => tag("svg");
    public static Node table => tag("table");
    public static Node tbody => tag("tbody");
    public static Node td => tag("td");
    public static Node template => tag("template");
    public static Node tfoot => tag("tfoot");
    public static Node th => tag("th");
    public static Node thead => tag("thead");
    public static Node time => tag("time");
    public static Node title => tag("title");
    public static Node tr => tag("tr");
    public static Node track => tag("track");
    public static Node tt => tag("tt");
    public static Node underline => tag("underline");
    public static Node var => tag("var");
    public static Node video => tag("video");
    public static Node wbr => tag("wbr");
    public static Node xmp => tag("xmp");


    public static Node ul => tag("ul");
    public static Node ol => tag("ol");
    public static Node p => tag("p");
    public static Node li => tag("li");


}
